version: '3'

volumes:
  vendor:

services:
  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    volumes:
      - ./src/api:/go/src/api
      - vendor:/go/src/api/vendor
    ports:
      - 3030:3030
    tty:
      true
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client:/client
      - ./client/dist:/client/dist
      - /client/node_modules
    ports:
      - 8080:8080
    tty:
      true
